services:
  - type: web
    name: api
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install  && npm run build
    startCommand: npm run start -w ./apps/api --port 4000
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false  # set in Dashboard or via render CLI